Feature/342 job filter
developersdo/empleo-dot-net pull request #534
Opened 2018-03-02 05:55 UTC by jeanrodriguez

TEST : 

1. go to index

1. click "mostrar mas empleos"

1.  in jobs view change "cantidad de registros"

2018-03-02 13:17 UTC, Willjobs94 commented
Good job @jeanrodriguez, remember to include a reference to the issue you're solving on your PR description and once you're finished, do an interactive rebase to squash your commits into one with the proper naming convention.

2018-03-16 02:02 UTC, eatskolnikov commented
@jeanrodriguez Great contribution! I liked that you respected the naming convention for the branch. I've assigned a few people to review this PR, and would like you to read this article while waiting for the approval. It talks about how to make a great PR and it is written by @claudiosanchez You may want to gain some points with him :p 
https://medium.com/@claudiosanchez/a-pull-request-that-will-make-you-smile-45d4f0f0ad18

2018-05-09 00:27 UTC, eatskolnikov requested changes

2018-05-09 00:27 UTC, eatskolnikov commented on EmpleoDotNet.Core/EmpleoDotNet.Core.csproj
> +    <Reference Include="System.Web.Mvc, Version=4.0.0.1, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL" />
@jeanrodriguez  ¿Qué sucede con esta referencia? ¿Para qué es?

2018-05-20 20:33 UTC, eatskolnikov commented on EmpleoDotNet.Core/EmpleoDotNet.Core.csproj
> +    <Reference Include="System.Web.Mvc, Version=4.0.0.1, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL" />
@jeanrodriguez este PR está super inactivo y tiene conflictos, arregla los conflictos y dime lo de esa referencia para darle merge

2018-08-30 02:16 UTC, closed without merging